services:
  - docker

before_install:
  - docker build -t aadarshp31/myreactapp -f Dockerfile.dev .

script:
  - docker run -e CI=true aadarshp31/myreactapp test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: "ap-south-1"
  app: "Github-TravisCI-EBS-Pipeline"
  env: "Github-TravisCI-EBS-Pipeline-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-533962485714"
  bucket_path: "Github-TravisCI-EBS-Pipeline"
  on: 
    branch: main