version: "3"
services:
  myreactapp_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /var/app/node_modules
      - .:/var/app
    stdin_open: true
    tty: true

  myreactapp_test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /var/app/node_modules
      - .:/var/app
    stdin_open: true
    tty: true
    command: [ "test" ]